# Development overrides - automatically loaded with compose.yaml
# Use: docker compose up

services:
  frontend:
    build:
      target: development
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      # Bind mount for live code reloading
      - .:/app
      # Anonymous volume for node_modules to allow write access
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    restart: "no"
    # Override healthcheck for dev server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5173/"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  node_modules:
