# Production overrides for Docker Compose
# Use: docker compose -f compose.yaml -f compose.production.yaml up -d

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: react-frontend:latest
    container_name: react-frontend-prod
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production
    restart: always
    # Remove volume mounts for production
    volumes: []
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
