# ============================================================================
# Docker Compose Configuration for Local Development
# ============================================================================
#
# This configuration enables developers to run the frontend application locally
# using Docker with full hot module replacement (HMR) support through Vite.
#
# Features:
# - Development server with Vite HMR on port 5173
# - Live code reloading via volume mounts
# - Environment variable configuration via .env file
# - Health checks for service monitoring
# - Non-root user execution for security
#
# Usage:
#   docker compose up          # Start services in foreground
#   docker compose up -d       # Start services in background
#   docker compose down        # Stop and remove containers
#   docker compose logs -f     # Follow logs
#
# ============================================================================

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: architecture-frontend-dev
    ports:
      - "5173:5173"  # Vite dev server
    volumes:
      # Mount source code for hot reload
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro

      # Mount configuration files
      - ./frontend/index.html:/app/index.html:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json:ro
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json:ro

      # Exclude node_modules from volume mount (use container's version)
      - /app/node_modules
    environment:
      # Vite configuration
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173

      # Load additional environment variables from .env file
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - architecture-network

networks:
  architecture-network:
    driver: bridge
    name: architecture-network
