# Pre-commit hooks for code quality enforcement
# See https://pre-commit.com for more information

# Installation:
#   poetry add --group dev pre-commit
#   poetry run pre-commit install
#
# Manual run:
#   poetry run pre-commit run --all-files
#
# Update hooks:
#   poetry run pre-commit autoupdate

repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format code with Black
        language_version: python3.12
        args: ["--config", "pyproject.toml"]
        exclude: |
          (?x)(
              ^migrations/|
              ^\.venv/|
              ^venv/|
              ^\.git/|
              ^__pycache__/
          )

  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: Lint with Ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        exclude: |
          (?x)(
              ^migrations/|
              ^\.venv/|
              ^venv/|
              ^\.git/|
              ^__pycache__/
          )
      - id: ruff-format
        name: Format imports with Ruff
        exclude: |
          (?x)(
              ^migrations/|
              ^\.venv/|
              ^venv/|
              ^\.git/|
              ^__pycache__/
          )

  # MyPy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        name: Type check with MyPy
        additional_dependencies:
          - django-stubs==5.1.1
          - djangorestframework-stubs==3.15.1
          - types-requests
        args: ["--config-file", "pyproject.toml"]
        exclude: |
          (?x)(
              ^migrations/|
              ^tests/|
              ^\.venv/|
              ^venv/|
              ^\.git/
          )

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        exclude: |
          (?x)(
              \.lock$|
              \.md$
          )
      - id: end-of-file-fixer
        name: Ensure files end with newline
      - id: check-yaml
        name: Validate YAML files
        args: ["--safe"]
      - id: check-json
        name: Validate JSON files
      - id: check-toml
        name: Validate TOML files
      - id: check-added-large-files
        name: Check for large files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: detect-private-key
        name: Detect private keys
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ["--fix=lf"]

  # Python-specific checks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
        name: Prevent blanket noqa
      - id: python-check-blanket-type-ignore
        name: Prevent blanket type ignore
      - id: python-no-eval
        name: Prevent eval() usage
      - id: python-use-type-annotations
        name: Enforce type annotations
      - id: python-check-mock-methods
        name: Check mock method usage

# Configuration
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: '3.0.0'
